name: Check pull request
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run_tests:
    name: "Run helm unit tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.1

      - name: Install plugin
        run: make ci/tests/unit/install-plugin

      - name: Run unit tests
        run: make ci/tests/unit

  check_unit_tests_snapshots:
    needs: [run_tests]
    name: "Check unit tests snapshots were committed"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.1

      - name: Run snapshot update
        run: make ci/tests/unit/update-snapshot/run

      - name: Process changes
        run: |
          if [[ -z "$(git status --porcelain)" ]];
          then
            exit 0
          else
            echo "You have uncommitted unit test snapshots:"
            echo "Run 'make tests/unit/update-snapshot'"
            echo "Commit changes and push"
            exit 1
          fi

  check_documentation:
    name: "Check documentation was rebuilt and committed"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'

      - name: Check documentation changes
        run: make doc/diff
